version: "3"
services:
  mysql:
    build:
      context: ./mysql/docker
    volumes:
      - ./mysql/:/mysql
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Japan
    networks:
      - default
    ports:
      - '3305:3306'
  fast_api:
    command: ["uvicorn", "app.main:app","--reload", "--host", "0.0.0.0", "--port", "8000"]
    # command: /bin/bash -c "uvicorn app.main:app --reload --host 0.0.0.0 --port 80"
    build:
      context: ./fastapi/docker
    volumes:
      - ./fastapi/:/app
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Japan
    ports:
      - "8000:8000"
    networks:
      - default
volumes:
  db-data:
networks:
  default:
