version: "3"
services:
  mysql:
    build:
      context: ./docker/mysql
    volumes:
      - ./docker/mysql/sqls/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/log/:/var/log/mysql
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=password
      - LC_ALL=ja_JP.UTF-8
      - TZ=Japan
    networks:
      - default
    ports:
      - "3305:3306"
  fast_api:
    command: ["uvicorn", "app.views:app","--reload", "--host", "0.0.0.0", "--port", "8000"]
    build:
      context: ./
      dockerfile: ./docker/fastapi/Dockerfile
    volumes:
      - ./app/:/app
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Japan
    ports:
      - "8000:8000"
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - "8080:80"
    networks:
      - default
    volumes:
      - /sessions

volumes:
  db-data:
networks:
  default:
